# Generated by Django 5.0.4 on 2024-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kra',
            name='Measurement',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='submission_date',
            field=models.DateTimeField(default=None),
        ),
    ]
