# Generated by Django 5.0.4 on 2024-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0004_alter_pan_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='passport_no',
            field=models.CharField(),
        ),
    ]
