# Generated by Django 5.0.4 on 2024-08-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0004_alter_custom_forms_alloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itdeclaration80d_new1',
            fields=[
                ('Emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Investment1', models.CharField(default='Medi claim Policy for Self, Spouse, Children-80D', max_length=100)),
                ('Investment1_Amount', models.IntegerField(default=0)),
                ('Investment2', models.CharField(default='Medi claim Policy for Self, Spouse, Children for senior citizen-80D', max_length=100)),
                ('Investment2_Amount', models.IntegerField(default=0)),
                ('Investment3', models.CharField(default='Medi claim Policy for Parents-80D', max_length=100)),
                ('Investment3_Amount', models.IntegerField(default=0)),
                ('Investment4', models.CharField(default='Medi claim Policy or Medical Bills for parents for senior citizen-80D', max_length=100)),
                ('Investment4_Amount', models.IntegerField(default=0)),
                ('Investment5', models.CharField(default='Preventive health check up - 80D', max_length=100)),
                ('Investment5_Amount', models.IntegerField(default=0)),
                ('Investment6', models.CharField(default='Preventive health check up for parents - 80D', max_length=100)),
                ('Investment6_Amount', models.IntegerField(default=0)),
                ('emp_emailid', models.ForeignKey(db_column='emp_emailid', null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Itdeclaration_oie_new1',
            fields=[
                ('Emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Investment1', models.CharField(default='Additional Exemptions on voluntary NPS', max_length=50)),
                ('Investment1_Amount', models.IntegerField(default=0)),
                ('Investment2', models.CharField(default='Rajiv Gandhi Equity savings scheme', max_length=50)),
                ('Investment2_Amount', models.IntegerField(default=0)),
                ('Investment3', models.CharField(default='Treatment of dependent with disability', max_length=50)),
                ('Investment3_Amount', models.IntegerField(default=0)),
                ('Investment4', models.CharField(default='Treatment of dependent with severe disability', max_length=50)),
                ('Investment4_Amount', models.IntegerField(default=0)),
                ('emp_emailid', models.ForeignKey(db_column='emp_emailid', null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Itdeclaration_osi_new1',
            fields=[
                ('Emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Investment1', models.CharField(default='Income from other sources', max_length=50)),
                ('Investment1_Amount', models.IntegerField()),
                ('Investment2', models.CharField(default='Interest Earned from Savings Deposit', max_length=50)),
                ('Investment2_Amount', models.IntegerField()),
                ('Investment3', models.CharField(default='Interest Earned from Fixed Deposit', max_length=50)),
                ('Investment3_Amount', models.IntegerField()),
                ('Investment4', models.CharField(default='Interest Earned from National Savings Certificates', max_length=50)),
                ('Investment4_Amount', models.IntegerField()),
                ('emp_emailid', models.ForeignKey(db_column='emp_emailid', null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee')),
            ],
        ),
    ]
