# Generated by Django 5.0.4 on 2024-08-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_itdeclaration80d_new1_itdeclaration_oie_new1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_letters1',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('letter_name', models.CharField(max_length=250)),
                ('letter_content', models.TextField(default=None, null=True)),
                ('alloc', models.CharField(default=None, max_length=250, null=True)),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.company')),
            ],
        ),
    ]
