# Generated by Django 5.0.4 on 2024-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0006_custom_letters1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todotasks1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
