# Generated by Django 5.0.4 on 2024-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0006_quiz_total_marks_alter_quiz_correct_alter_quiz_eid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='wrong',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
