# Generated by Django 4.2.2 on 2024-09-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "happyPerformerBackend",
            "0006_itdeclaration_osi_new1_itdeclaration_oie_new1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary1",
            fields=[
                ("sal_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("payout_month", models.CharField(max_length=50)),
                (
                    "effective_from",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("revision", models.IntegerField(blank=True, null=True)),
                ("basic", models.FloatField()),
                ("hra", models.FloatField()),
                ("conveyance", models.FloatField()),
                ("da", models.FloatField()),
                ("special_allowance", models.FloatField()),
                ("monthly_ctc", models.FloatField()),
                ("annual_ctc", models.FloatField()),
                ("Eligible_Deductions", models.FloatField()),
                ("Yearly_Taxable_Salary", models.FloatField()),
                ("Total_Tax_Liability", models.FloatField()),
                ("Monthly_TDS", models.FloatField()),
                ("Monthly_EPF", models.FloatField()),
                ("Monthly_Professional_Tax", models.FloatField()),
                ("Net_Salary", models.FloatField()),
                ("paymentmethod", models.CharField(default="Bank", max_length=50)),
                ("notes", models.CharField(max_length=50)),
                ("remarks", models.CharField(max_length=50)),
                ("holdsalary", models.IntegerField(default=0)),
                ("paid", models.IntegerField(default=0)),
                (
                    "emp_emailid",
                    models.ForeignKey(
                        db_column="emp_emailid",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="happyPerformerBackend.bank_details",
                        to_field="emp_emailid",
                    ),
                ),
            ],
        ),
    ]
