# Generated by Django 4.2.2 on 2024-09-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("happyPerformerBackend", "0007_salary1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poifiles_new1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Year", models.CharField(max_length=7)),
                ("Investment_1", models.CharField(default="80C", max_length=10)),
                ("actualAmount_80C", models.IntegerField(default="0")),
                ("Doc_80C", models.CharField(max_length=255, null=True)),
                ("Status1", models.CharField(default="Pending", max_length=20)),
                ("Investment_2", models.CharField(default="80D", max_length=4)),
                ("actualAmount_80D", models.IntegerField(default="0")),
                ("Doc_80D", models.CharField(max_length=255, null=True)),
                ("Status2", models.CharField(default="Pending", max_length=20)),
                ("Investment_3", models.CharField(default="OIE", max_length=4)),
                ("OIE_actualAmount", models.IntegerField(default="0")),
                ("OIE_Doc", models.CharField(max_length=255, null=True)),
                ("Status3", models.CharField(default="Pending", max_length=20)),
                ("Investment_4", models.CharField(default="OSI", max_length=4)),
                ("OSI_actualAmount", models.IntegerField(default="0")),
                ("OSI_Doc", models.CharField(max_length=255, null=True)),
                ("Status4", models.CharField(default="Pending", max_length=20)),
                (
                    "Emp_id",
                    models.ForeignKey(
                        db_column="emp_emailid",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="happyPerformerBackend.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["Emp_id"], name="happyPerfor_emp_ema_4b3a85_idx"
                    )
                ],
            },
        ),
    ]
