# Generated by Django 5.0.4 on 2024-09-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0007_alter_quiz_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
