# Generated by Django 5.0.4 on 2024-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0008_quizattempt_total_correct_quizattempt_total_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='total_unattempted',
            field=models.IntegerField(default=0),
        ),
    ]
