# Generated by Django 5.0.4 on 2024-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0008_attritionchoicedata_attritiondepartmentdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('80C', '80C Investments'), ('80D', '80D Investments'), ('other-income', 'Other Sources of Income'), ('other-investments', 'Other Investments and Exemptions')], max_length=50)),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='poi_files/')),
            ],
        ),
    ]
