# Generated by Django 4.2.2 on 2024-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0008_poifiles_new1'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
