# Generated by Django 5.0.4 on 2024-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0009_quizattempt_total_unattempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
